name: app_store_db
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0

  # 状態管理
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1

  # UI
  fl_chart: ^0.70.0
  go_router: ^14.6.2
  intl: ^0.18.1

  # 画像
  cached_network_image: ^3.4.1

  # Generate
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Generate
  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
