enum Genre {
  business,
  socialNetworking,
  healthAndFitness,
  lifeStyle,
  travel,
  games,
  shopping,
  stickers,
  graphicsAndDesign,
  weather,
  utilities,
  sports,
  reference,
  productivity,
  photoAndVideo,
  news,
  navigation,
  music,
  finance,
  entertainment,
  education,
  books,
  medical,
  magazinesAndNewspapers,
  catalogs,
  foodAndDrink,
  developerTools,
}

extension GenreExtension on Genre {
  int get code => {
        Genre.business: 6000,
        Genre.weather: 6001,
        Genre.utilities: 6002,
        Genre.travel: 6003,
        Genre.sports: 6004,
        Genre.socialNetworking: 6005,
        Genre.reference: 6006,
        Genre.productivity: 6007,
        Genre.photoAndVideo: 6008,
        Genre.news: 6009,
        Genre.navigation: 6010,
        Genre.music: 6011,
        Genre.lifeStyle: 6012,
        Genre.healthAndFitness: 6013,
        Genre.games: 6014,
        Genre.finance: 6015,
        Genre.entertainment: 6016,
        Genre.education: 6017,
        Genre.books: 6018,
        Genre.medical: 6020,
        Genre.magazinesAndNewspapers: 6021,
        Genre.catalogs: 6022,
        Genre.foodAndDrink: 6023,
        Genre.shopping: 6024,
        Genre.stickers: 6025,
        Genre.developerTools: 6026,
        Genre.graphicsAndDesign: 6027,
      }[this]!;

  String get title => {
        Genre.business: 'ビジネス',
        Genre.socialNetworking: 'ソーシャルネットワーキング',
        Genre.healthAndFitness: 'ヘルス＆フィットネス',
        Genre.lifeStyle: 'ライフスタイル',
        Genre.travel: 'トラベル',
        Genre.games: 'ゲーム',
        Genre.shopping: 'ショッピング',
        Genre.stickers: 'ステッカー',
        Genre.graphicsAndDesign: 'グラフィック＆デザイン',
        Genre.weather: '天気',
        Genre.utilities: 'ユーティリティ',
        Genre.sports: 'スポーツ',
        Genre.reference: 'リファレンス',
        Genre.productivity: '仕事効率化',
        Genre.photoAndVideo: '写真とビデオ',
        Genre.news: 'ニュース',
        Genre.navigation: 'ナビゲーション',
        Genre.music: 'ミュージック',
        Genre.finance: 'ファイナンス',
        Genre.entertainment: 'エンターテイメント',
        Genre.education: '教育',
        Genre.books: 'ブック',
        Genre.medical: 'メディカル',
        Genre.magazinesAndNewspapers: '雑誌と新聞',
        Genre.catalogs: 'カタログ',
        Genre.foodAndDrink: 'フード＆ドリンク',
        Genre.developerTools: '開発ツール',
      }[this]!;
}

enum Version {
  v1,
  v2,
}
